CREATE TABLE pais
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL,
    CONSTRAINT pais_pkey PRIMARY KEY (id)
);

INSERT INTO pais(codigo, nombre) VALUES ('CO', 'Colombia');
INSERT INTO pais(codigo, nombre) VALUES ('PE', 'Peru');
INSERT INTO pais(codigo, nombre) VALUES ('CL', 'Chile');

CREATE TABLE ciudad
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) NOT NULL,
    descripcion text,
    pais bigint NOT NULL,
    CONSTRAINT ciudad_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pais FOREIGN KEY (pais)
        REFERENCES public.pais (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Bogota','capital de la República de Colombia y del departamento de Cundinamarca, además de ser el epicentro político, administrativo, económico, industrial, artístico, cultural, deportivo y, por supuesto, turístico del país. Se trata de una ciudad diversa y multicultural en la que se combinan las construcciones modernas con las del pasado colonial. Además, es importante tener en cuenta que gracias a sus cerros y a sus parques, es una ciudad verde.', (SELECT id FROM pais where codigo='CO'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Medellin','La segunda ciudad más poblada de Colombia es Medellín, capital del departamento de Antioquia. Situada en la cordillera central de los Andes, es un destino ideal para hacer senderismo, tirolina y montar a caballo. Además, los turistas podrán disfrutar de unas vacaciones llenas de cultura.', (SELECT id FROM pais where codigo='CO'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Cali','Cali, cuyo nombre oficial es Santiago de Cali. Se trata de la capital del departamento del Valle del Cauca y está considerada como una de las ciudades más antiguas de América. Por otro lado, debes saber que se trata de uno de los principales centros económicos e industriales del país.', (SELECT id FROM pais where codigo='CO'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Barranquilla','Barranquilla es la cuarta ciudad más poblada del país. Aquí se celebra una de las festividades culturales más importantes de Colombia, el Carnaval de Barranquilla, que ha sido declarado Patrimonio Oral e Inmaterial de la Humanidad por la UNESCO. Además, la ciudad destaca por su belleza arquitectónica, sus paisajes naturales y la alegría de la gente.', (SELECT id FROM pais where codigo='CO'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Cartagena','Cartagena de Indias, capital del departamento de Bolívar. Situada a orillas del mar Caribe, ha conservado su centro histórico, la Ciudad Amurallada, que ha sido declarada Patrimonio de la Humanidad por la UNESCO. También queremos destacar sus excelentes playas.',(SELECT id FROM pais where codigo='CO'));

INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Lima','Lima (departamento de Lima) es la capital y ciudad más poblada de Perú con 8,8 millones de habitantes. Posee una densidad de población de 3200 hab/km², siendo una de las más altas de América Latina.', (SELECT id FROM pais where codigo='PE'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Arequipa','Arequipa es la ciudad más poblada del departamento de Arequipa y la segunda más poblada del país con poco más de 1 millones de habitantes.', (SELECT id FROM pais where codigo='PE'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Trujillo','La ciudad de Trujillo se encuentra en el departamento de La Libertad, dónde es la ciudad más poblada con 919 mil habitantes.', (SELECT id FROM pais where codigo='PE'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Chiclayo','Chiclayo, situado en el departamento de Lambayeque, es la cuarta ciudad más poblada del país con 552 mil habitantes.', (SELECT id FROM pais where codigo='PE'));

INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Santiago de Chile','Santiago, también conocida como Gran Santiago o Santiago de Chile, es la capital y ciudad más poblada de Chile. Localizada en el centro de país, la ciudad cuenta con una población de 6,2 millones de habitantes.', (SELECT id FROM pais where codigo='CL'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Puente Alto','Puente Alto es una comuna y ciudad chilena, capital de la provincia de Cordillera, la cual pertenece a la región Metropolitana de Santiago. Según el último censo, Puente Alto tiene una población de 568 106 habitantes.', (SELECT id FROM pais where codigo='CL'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Antofagasta','Antofagasta, popularmente conocida como “La Perla del Norte”, es la capital de la región y provincia de Antofagasta. Con más de 380 mil habitantes, es la tercera ciudad más poblada del país.', (SELECT id FROM pais where codigo='CL'));
INSERT INTO ciudad(nombre, descripcion, pais) VALUES ('Viña del Mar','Viña del Mar, también conocida como “Ciudad Jardín”, es una ciudad perteneciente a la provincia y región de Valparaíso. Además de ser una de las zonas más turísticas del país, es la cuarta más poblada con 334 mil habitantes.', (SELECT id FROM pais where codigo='CL'));
